// <auto-generated />
namespace Thak_tshehWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserAddShowFollow : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserAddShowFollow));
        
        string IMigrationMetadata.Id
        {
            get { return "202111091709026_UserAddShowFollow"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
